name: PR Review

on:
  issue_comment:
    types: [created, edited]

jobs:
  approve:
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment is "approved"
        if: ${{ github.event.comment.body == 'approved' }}
        run: echo "Comment is approved"

      - name: Approve the pull request
        if: ${{ github.event.comment.body == 'approved' && (github.event.comment.user.login == 'thomaswinkler' || contains(github.event.comment.user.login, github.repository_owner)) }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: 'APPROVE'
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
